version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: wespeak_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wespeakwelisten
      MYSQL_USER: wespeak
      MYSQL_PASSWORD: wespeakpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend-master/mysql/table_setup.mysql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend-master/mysql/patches/5-17-21.mysql:/docker-entrypoint-initdb.d/02-patches.sql
    networks:
      - wespeak_network

  api:
    build: .
    container_name: wespeak_api
    environment:
      DATABASE_URL: mysql+pymysql://wespeak:wespeakpass@mysql:3306/wespeakwelisten
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - .:/app
    networks:
      - wespeak_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:

networks:
  wespeak_network:
    driver: bridge